# Generated by Django 4.0.3 on 2022-03-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istakip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='workerName',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='workers',
            name='workerTelNo',
            field=models.CharField(default='', max_length=200),
        ),
    ]
