# Generated by Django 4.0.3 on 2022-04-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istakip', '0002_alter_workers_workername_alter_workers_workertelno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruiteName', models.CharField(default='', max_length=200)),
                ('fruiteKg', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SuperUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superUserId', models.CharField(default='', max_length=200)),
                ('superUserPassword', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
