# Generated by Django 3.2.12 on 2022-04-06 04:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('istakip', '0003_fruits_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workerFruiteKg', models.CharField(default='', max_length=200)),
                ('workerPayment', models.CharField(default='', max_length=200)),
                ('recordSaveTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('worker', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='istakip.workers')),
            ],
        ),
    ]
