# Generated by Django 3.2.12 on 2022-04-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istakip', '0004_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='worker',
            field=models.CharField(default='', max_length=200),
        ),
    ]
