# Generated by Django 3.2.12 on 2022-04-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istakip', '0005_alter_record_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='workerFruiteId',
            field=models.CharField(default='', max_length=200),
        ),
    ]
