# Generated by Django 3.2.12 on 2022-04-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istakip', '0006_record_workerfruiteid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminId', models.CharField(default='', max_length=200)),
                ('adminPassword', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
